language: java

sudo: false

jdk:
  - oraclejdk9
  - oraclejdk8
  - openjdk7

install: true

script: mvn verify -Ppitest

after_success:
  - mvn coveralls:report

cache:
  directories:
    - '$HOME/.m2/repository'
